spring.application.name=cloudServicePJ
server.port=8081
# DB설정
spring.datasource.url=jdbc:mysql://localhost:3306/CloudPj?allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=Root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/
spring.mvc.view.prefix=/static/
spring.mvc.view.suffix=.html

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp

# xml 실행 로그 작동
logging.level.outsider.cloudServicePJ.Mapper=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 업로드 파일경로
file.uploadPath=/cloud_storage/uploads/
# 파일 하나의 최대 용량
spring.servlet.multipart.max-file-size=-1
# 한 번의 전송(여러 파일 포함)에 포함된 전체 용량
spring.servlet.multipart.max-request-size=-1